### ISSUE TITLE
Publish builds to NPM via CI

### ISSUE THREAD

**Issue by shanejonas** [MetaMask/api-specs#221]
### Add npm publish step to our publish action

When this repo was made we hadn't really figured out the npm publish part. but we should be able to use whats in the `metamask-module-template` now since it has support for npm publishing.

add this at the bottom of [.github/workflows/publish-release.yml](https://github.com/MetaMask/api-specs/blob/main/.github/workflows/publish-release.yml). and follow the instructions in the comment below to set up the token.

```yaml
      - name: Publish NPM
        uses: MetaMask/action-npm-publish@v2
        with:
          # This `NPM_TOKEN` needs to be manually set per-repository.
          # Look in the repository settings under "Environments", and set this token in the `npm-publish` environment.
          npm-token: ${{ secrets.NPM_TOKEN }}
        env:
          SKIP_PREPACK: true
```

> source: https://github.com/MetaMask/metamask-module-template/blob/c2b55bce243483c4edcc3c454bba415ff996335b/.github/workflows/publish-release.yml#L64-L86
